replicaCount: 1
image:
  repository: <your-docker-repo>/hello-world
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: hello-world.local
      paths:
        - /
  tls: []
containerPort: 5000
