name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker Image
        run: |
          COMMIT_ID=$(echo $GITHUB_SHA | cut -c1-7)
          docker build -t guysaar8/comet-home:$COMMIT_ID .
          echo "Docker image built and tagged with commit ID: $COMMIT_ID"

  semantic-release:
    name: Semantic Release
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.semantic.outputs.nextRelease.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run Semantic Release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

  tag-and-push:
    name: Tag and Push Docker Image
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Tag Docker Image
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            TAG=rc-${{ github.event.pull_request.number }}
          else
            TAG=${{ needs.semantic-release.outputs.release_version }}
          fi
          docker tag guysaar8/comet-home:$COMMIT_ID guysaar8/comet-home:$TAG
      - name: Push Docker Image
        run: |
          docker push guysaar8/comet-home:$TAG

  deploy:
    name: Deploy to EKS with Helm
    runs-on: ubuntu-latest
    needs: tag-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'
      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}
        env:
          EKS_CLUSTER_NAME: main-eks
      - name: Deploy with Helm
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            NAMESPACE=dev
            TAG=rc-${{ github.event.pull_request.number }}
          else
            NAMESPACE=prd
            TAG=${{ needs.semantic-release.outputs.release_version }}
          fi
          helm upgrade --install hello-world ./helm-hello-world \
            --namespace $NAMESPACE \
            --create-namespace \
            --set image.repository=guysaar8/comet-home \
            --set image.tag=$TAG
